<?php

    namespace Database\Seeders;

    use Illuminate\Database\Seeder;
    use Illuminate\Support\Facades\DB;

    class ServicioSeeder extends Seeder
    {
        public function run(): void
        {
            DB::table('servicios')->insert([
                [
                    'idser' => 'CRUNCHY',
                    'nombreser' => 'Crunchyroll',
                    'completoser' => 4.00,
                    'precioser' => 1.50,
                    'comboser' => 1.00,
                    'reventaser' => 1.00,
                    'revcompser' => 3.50,
                    'created_at' => '2024-12-19 23:32:48',
                    'updated_at' => '2024-12-19 23:32:48',
                ],
                [
                    'idser' => 'DISNEYP',
                    'nombreser' => 'Disney Premium',
                    'completoser' => 11.00,
                    'precioser' => 3.50,
                    'comboser' => 2.75,
                    'reventaser' => 2.50,
                    'revcompser' => 9.00,
                    'created_at' => '2024-12-19 23:32:53',
                    'updated_at' => '2024-12-19 23:32:53',
                ],
                [
                    'idser' => 'DISNEYS',
                    'nombreser' => 'Disney Standard',
                    'completoser' => 6.00,
                    'precioser' => 2.00,
                    'comboser' => 1.75,
                    'reventaser' => 1.50,
                    'revcompser' => 4.25,
                    'created_at' => '2024-12-19 23:32:37',
                    'updated_at' => '2024-12-19 23:32:37',
                ],
                [
                    'idser' => 'MAGIS',
                    'nombreser' => 'Flujo Tv',
                    'completoser' => 8.00,
                    'precioser' => 3.25,
                    'comboser' => 2.75,
                    'reventaser' => 2.50,
                    'revcompser' => 5.00,
                    'created_at' => '2024-12-19 23:33:04',
                    'updated_at' => '2024-12-19 23:33:04',
                ],
                [
                    'idser' => 'MAX',
                    'nombreser' => 'Max Standard',
                    'completoser' => 6.00,
                    'precioser' => 2.50,
                    'comboser' => 2.00,
                    'reventaser' => 2.00,
                    'revcompser' => 4.00,
                    'created_at' => '2024-12-19 23:33:13',
                    'updated_at' => '2024-12-19 23:33:13',
                ],
                [
                    'idser' => 'NETFLIX',
                    'nombreser' => 'Netflix Premium',
                    'completoser' => 11.00,
                    'precioser' => 3.25,
                    'comboser' => 2.75,
                    'reventaser' => 2.50,
                    'revcompser' => 9.00,
                    'created_at' => '2024-12-19 23:33:51',
                    'updated_at' => '2024-12-19 23:33:51',
                ],
                [
                    'idser' => 'OTRO',
                    'nombreser' => 'Otras Que Se Venden',
                    'completoser' => 0.00,
                    'precioser' => 0.00,
                    'comboser' => 0.00,
                    'reventaser' => 0.00,
                    'revcompser' => 0.00,
                    'created_at' => '2024-12-19 23:33:39',
                    'updated_at' => '2024-12-19 23:33:39',
                ],
                [
                    'idser' => 'PARAMOUNT',
                    'nombreser' => 'Paramount Plus',
                    'completoser' => 4.00,
                    'precioser' => 1.75,
                    'comboser' => 1.25,
                    'reventaser' => 1.10,
                    'revcompser' => 3.50,
                    'created_at' => '2024-12-19 23:33:29',
                    'updated_at' => '2024-12-19 23:33:29',
                ],
                [
                    'idser' => 'PRIME',
                    'nombreser' => 'Prime Video',
                    'completoser' => 6.00,
                    'precioser' => 2.25,
                    'comboser' => 1.50,
                    'reventaser' => 1.25,
                    'revcompser' => 3.50,
                    'created_at' => '2024-12-19 23:33:23',
                    'updated_at' => '2024-12-19 23:33:23',
                ],
                [
                    'idser' => 'SPOTIFY',
                    'nombreser' => 'Spotify Premium',
                    'completoser' => 11.00,
                    'precioser' => 3.00,
                    'comboser' => 2.75,
                    'reventaser' => 2.50,
                    'revcompser' => 11.00,
                    'created_at' => '2024-12-19 23:33:18',
                    'updated_at' => '2024-12-19 23:33:18',
                ],
                [
                    'idser' => 'VIX',
                    'nombreser' => 'Vix',
                    'completoser' => 7.50,
                    'precioser' => 2.75,
                    'comboser' => 2.25,
                    'reventaser' => 2.25,
                    'revcompser' => 5.00,
                    'created_at' => '2024-12-19 23:34:02',
                    'updated_at' => '2024-12-19 23:34:02',
                ],
                [
                    'idser' => 'DISNEYESPN',
                    'nombreser' => 'Disney Standard Espn',
                    'completoser' => 5.25,
                    'precioser' => 2.50,
                    'comboser' => 2.25,
                    'reventaser' => 2.00,
                    'revcompser' => 4.50,
                    'created_at' => '2024-12-19 23:35:52',
                    'updated_at' => '2024-12-19 23:35:52',
                ],
            ]);
        }
    }
?>